name: belajar-ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ambil kode
        uses: actions/checkout@v3

      - name: build docker
        run: docker build -t myapp .

      - name: run container
        run: docker run -d -p 8080:80 myapp

      - name: test web
        run: |
          sleep 5
          curl localhost:8080
